### ISSUE TITLE
"empty segment not permitted" when a podspec defines its source_files with trailing slash

### ISSUE THREAD

**Issue by kerrmarin** [pinterest/PodToBUILD#104]
As the title says, when you have a podspec that defines its source files with a trailing slash, you get the error `empty segment not permitted`. For example, trying to build the `Moya` (I realise this is a Swift library, but bear with me) yields:
```
ERROR: /path/to/project/ios/Vendor/Moya/BUILD:165:10: Traceback (most recent call last):
	File "/path/to/project/ios/Vendor/Moya/BUILD", line 162
		objc_library(name = "Core_cxx", enable_modules ..., <8 more arguments>)
	File "/path/to/projectios/Vendor/Moya/BUILD", line 165, in objc_library
		glob(["Sources/Moya//**/*.cc", "Sourc..."], <2 more arguments>)
empty segment not permitted
```

You'll notice that the glob's path is `Sources/Moya//**/*.cc` which yields the error. The Moya podspec defines its source files as:

```
  s.subspec "Core" do |ss|
    ss.source_files  = "Sources/Moya/", "Sources/Moya/Plugins/"
    ss.dependency "Alamofire", "5.0.0-rc.2"
    ss.framework  = "Foundation"
  end
```

I've tested this with a simple spec and the same error occurs when the trailing slash is added to the `source_files`. The error disappears if the podspec is updated to remove the trailing slash.

**Comment by rahul-malik** [comment]
@kerrmarin - Thanks for reporting! The issue should be addressable within our GlobUtils or the callers if you'd like to propose a PR https://github.com/pinterest/PodToBUILD/blob/9a6a90a1cd104b48bc27d6fa83920844080c046a/Sources/PodToBUILD/GlobUtils.swift

**Comment by migfabio** [comment]
Hi, any news on this issue?
