### ISSUE TITLE
TypeError: load() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by Jacky-LinPeng** [pinterest/PodToBUILD#209]
Hello, I set WORKSPACE and pod.workspace according to the tutorial
After I execute: 
```
bazel run @rules_pods//:update_pods -- --src_root $PWD
```

 
PIC:
![image](https://user-images.githubusercontent.com/15797691/176193792-babe93a4-2b91-4555-8475-e4aeb032722a.png)
<img width="676" alt="image" src="https://user-images.githubusercontent.com/15797691/176193880-000ebf56-2351-43fa-b14d-97b5fb5bf9b1.png">

![image](https://user-images.githubusercontent.com/15797691/176194231-9aeb4067-7082-4020-b604-4ab0693a28e6.png)

log:

```
[source-only][~/Documents/bazel/examples/PodToBUILD-master/aa]$ sudo bazel run @rules_pods//:update_pods -- --src_root $PWD                   rvm:
Password:
Starting local Bazel server and connecting to it...
DEBUG: Rule 'rules_pods' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "b523e1c567dce08f6afcde607fb9f62e1c33074891b1fcc1ee647aa2cc2f7e26"
DEBUG: Repository rules_pods instantiated at:
  /Users/mac/Documents/bazel/examples/PodToBUILD-master/aa/WORKSPACE:3:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_root/65baa7e1beeb8bf9ba32b64053619473/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Analyzed target @rules_pods//:update_pods (42 packages loaded, 272 targets configured).
INFO: Found 1 target...
Target @rules_pods//bin:update_pods up-to-date:
  bazel-bin/external/rules_pods/bin/update_pods
INFO: Elapsed time: 30.721s, Critical Path: 0.05s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
Updating pods in /Users/mac/Documents/bazel/examples/PodToBUILD-master/aa
Building PodToBUILD dependencies...
running: make release
skipping build..

Traceback (most recent call last):
  File "/private/var/tmp/_bazel_root/65baa7e1beeb8bf9ba32b64053619473/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/rules_pods/bin/update_pods", line 528, in <module>
    main()
  File "/private/var/tmp/_bazel_root/65baa7e1beeb8bf9ba32b64053619473/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/rules_pods/bin/update_pods", line 523, in main
    load("Pods.WORKSPACE")
  File "/private/var/tmp/_bazel_root/65baa7e1beeb8bf9ba32b64053619473/execroot/__main__/bazel-out/darwin-fastbuild/bin/external/rules_pods/bin/update_pods", line 492, in load
    exec(workspace_str, d, d)
  File "<string>", line 1, in <module>
TypeError: load() takes exactly 1 argument (2 given)
```

**ERROR: TypeError: load() takes exactly 1 argument (2 given)**

**Comment by Jacky-LinPeng** [comment]
It's my fault。。。。
